### create
POST https://stellarburgers.nomoreparties.site/api/auth/register
Content-Type: application/json

{
  "name": "tun.anatoly7",
  "email": "tun.anatoly7@yandex.kz",
  "password": "qwerty"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### update
PATCH https://stellarburgers.nomoreparties.site/api/auth/user
Content-Type: application/json
Authorization: {{accessToken}}

{
  "name": "tun.anatoly6_6",
  "email": "tun.anatoly6_6@yandex.kz",
}

### info
GET https://stellarburgers.nomoreparties.site/api/auth/user
Content-Type: application/json
Authorization: {{accessToken}}

### login
POST https://stellarburgers.nomoreparties.site/api/auth/login
Content-Type: application/json

{
  "email": "tun.anatoly7@yandex.kz",
  "password": "qwerty"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### logout
POST https://stellarburgers.nomoreparties.site/api/auth/logout
Content-Type: application/json

{
  "token": {{refreshToken}}
}

### delete
DELETE https://stellarburgers.nomoreparties.site/api/auth/user
Content-Type: application/json
Authorization: {{accessToken}}